runtime: python311
service: mesh-activity-pub-server

env_variables:
  DATABASE_URL: "postgresql+asyncpg://user:password@localhost/readr_mesh"
  GRAPHQL_ENDPOINT: "http://localhost:4000/graphql"
  ACTIVITYPUB_DOMAIN: "activity.readr.tw"
  SECRET_KEY: "your-secret-key-here"
  REDIS_URL: "redis://localhost:6379"

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 0
  max_instances: 10
  target_throughput_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

handlers:
  - url: /.*
    script: auto
    secure: always
